
version: "3.2"

services:
  gitlab:
    container_name: gitlab
    image: gitlab/gitlab-ce:9.2.7-ce.0

    hostname: gitlab

    environment:
      GITLAB_OMNIBUS_CONFIG: |
        external_url 'http://127.0.0.1:8050'
        gitlab_rails['gitlab_shell_ssh_port'] = 522

    ports:
      - "8050:8050"
      - "522:22"

    volumes:
      - ./config:/etc/gitlab
      - ./logs:/var/log/gitlab
      - ./data:/var/opt/gitlab

    logging:
      driver: "json-file"
      options:
        max-size: "200k"
        max-file: "10"

    # It allows to run some containers with (almost) all the capabilities of
    # their host machine, regarding kernel features and device access.
    privileged: true
