
db:
  # get the latest mysql server
  image: mysql:5.6

  # Set db environment
  environment:
    MYSQL_ROOT_PASSWORD: my-secret-pw

  # to export volume, as recommeded in https://registry.hub.docker.com/u/library/mysql/
  volumes:
    - "./mysql-data:/var/lib/mysql"
    - "/etc/localtime:/etc/localtime:ro"


web:
  # a custom image for django
  build: ./web

  # exec a different command from image
  command: uwsgi --ini /var/uwsgi/mysite_uwsgi.ini

  # set working dir for uwsgi
  working_dir: /var/uwsgi/

  # define volumes
  volumes:
    - "./django-data/:/var/uwsgi/"
    - "/etc/localtime:/etc/localtime:ro"

  # Expose the default port

  # link container to database
  links:
    - db


nginx:
  # get the latest nginx image
  build: ./nginx
  volumes:
    - "/etc/localtime:/etc/localtime:ro"
  volumes_from:
    - web
  ports:
    - "10080:80"
  links:
    - web
